"""
Risk & Prediction API Router - Multi-horizon deterioration risk, 15-minute forecasting, and Integrated Gradients XAI.
"""

from fastapi import APIRouter, HTTPException, Depends
from backend.schemas.prediction import RiskPredictionResponse, VitalForecastHorizon
from backend.services.digital_twin_service import DigitalTwinService

router = APIRouter(tags=["Risk & Trajectory Forecasting"])


def get_digital_twin_service() -> DigitalTwinService:
    from backend.main import twin_service
    return twin_service


@router.get("/api/patients/{patient_id}/risk", response_model=RiskPredictionResponse, summary="Get multi-horizon risk and XAI attribution")
def get_patient_risk(patient_id: str, service: DigitalTwinService = Depends(get_digital_twin_service)):
    """
    Retrieve real-time multi-horizon deterioration risk probabilities (1h, 3h, 6h),
    NEWS 2 score breakdown, and Integrated Gradients vital parameter risk attributions.
    """
    if patient_id not in service.replay.patients_meta:
        raise HTTPException(status_code=404, detail=f"Patient '{patient_id}' not found")
    
    matrix = service.replay.get_sliding_window_matrix(patient_id)
    return service.prediction.predict_risk(patient_id, matrix)


@router.get("/api/patients/{patient_id}/forecast", response_model=VitalForecastHorizon, summary="Get 15-minute future vital forecast")
def get_vital_forecast(patient_id: str, service: DigitalTwinService = Depends(get_digital_twin_service)):
    """
    Retrieve 15-minute future vital trajectory predictions generated by the CNN-BiLSTM forecasting head.
    """
    if patient_id not in service.replay.patients_meta:
        raise HTTPException(status_code=404, detail=f"Patient '{patient_id}' not found")
    
    matrix = service.replay.get_sliding_window_matrix(patient_id)
    pred = service.prediction.predict_risk(patient_id, matrix)
    return pred.forecast
